name: daggerheart_app
description: A Daggerheart character creation app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.9
  
  # File & Data
  path_provider: ^2.1.2
  
  # JSON & Code Generation
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.1
  shared_preferences: ^2.2.2
  share_plus: ^10.0.0
  file_picker: ^8.0.0
  
  pdf: ^3.10.8
  printing: ^5.13.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generators (dev only)
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  freezed: ^2.4.6
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/core/
    - assets/data/the_void/